# Generated by Django 4.2.1 on 2023-05-31 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlumniManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_job',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AlumniManagement.country'),
        ),
    ]
