# Generated by Django 4.2.1 on 2023-06-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlumniManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='previous_job',
            name='field_type',
            field=models.CharField(choices=[('technology', 'Technology'), ('medical', 'Medical/Healthcare'), ('mechanical', 'Mechanical Engineering'), ('electrical', 'Electrical Engineering'), ('finance', 'Finance/Accounting'), ('education', 'Education/Teaching'), ('marketing', 'Marketing/Advertising'), ('sales', 'Sales'), ('business', 'Business Development'), ('hr', 'Human Resources'), ('law', 'Law/Legal'), ('consulting', 'Consulting'), ('manufacturing', 'Manufacturing'), ('hospitality', 'Hospitality/Travel'), ('retail', 'Retail'), ('media', 'Media/Entertainment'), ('art', 'Art/Design'), ('architecture', 'Architecture'), ('nonprofit', 'Nonprofit/Volunteering'), ('government', 'Government/Public Administration')], default='technology', max_length=64),
        ),
    ]
