# Generated by Django 4.2.1 on 2023-05-20 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AlumniManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni_Demographic_Profile',
            fields=[
                ('alumni_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=64)),
                ('lname', models.CharField(max_length=64)),
                ('mi', models.CharField(blank=True, max_length=2)),
                ('suffix', models.CharField(blank=True, max_length=3)),
                ('address', models.CharField(max_length=64)),
                ('religion', models.CharField(max_length=64)),
                ('marital_status', models.CharField(max_length=64)),
                ('date_of_birth', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=64)),
                ('course_desc', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Current_Job',
            fields=[
                ('current_job_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=64)),
                ('salary', models.IntegerField()),
                ('start_date', models.DateField()),
                ('company_name', models.CharField(max_length=64)),
                ('company_address', models.CharField(max_length=64)),
                ('alumni', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AlumniManagement.alumni_demographic_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('curriculum_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('curriculum_name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('graduate_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('graduation_date', models.DateField()),
                ('degree', models.CharField(max_length=64)),
                ('honor', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('segment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlumniManagement.course')),
                ('current_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlumniManagement.current_job')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlumniManagement.curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Previous_Job',
            fields=[
                ('previous_job_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=64)),
                ('salary', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('company_name', models.CharField(max_length=64)),
                ('company_address', models.CharField(max_length=64)),
                ('alumni', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AlumniManagement.alumni_demographic_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Educational_Attainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumni_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlumniManagement.alumni_demographic_profile')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlumniManagement.course')),
                ('graduate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlumniManagement.graduate')),
            ],
        ),
    ]
