# Generated by Django 4.2.1 on 2023-05-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlumniManagement', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_job',
            name='field_type',
            field=models.CharField(choices=[('technology', 'Technology'), ('medical', 'Medical/Healthcare'), ('mechanical', 'Mechanical Engineering'), ('electrical', 'Electrical Engineering'), ('finance', 'Finance/Accounting'), ('education', 'Education/Teaching'), ('marketing', 'Marketing/Advertising'), ('sales', 'Sales'), ('business', 'Business Development'), ('hr', 'Human Resources'), ('law', 'Law/Legal'), ('consulting', 'Consulting'), ('manufacturing', 'Manufacturing'), ('hospitality', 'Hospitality/Travel'), ('retail', 'Retail'), ('media', 'Media/Entertainment'), ('art', 'Art/Design'), ('architecture', 'Architecture'), ('nonprofit', 'Nonprofit/Volunteering'), ('government', 'Government/Public Administration')], default='technology', max_length=64),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='curriculum_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='curriculum_name',
            field=models.CharField(max_length=255),
        ),
    ]
