# Generated by Django 4.2.1 on 2023-05-20 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlumniManagement', '0003_current_job_field_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educational_attainment',
            name='course_id',
        ),
        migrations.AddField(
            model_name='alumni_demographic_profile',
            name='course_id',
            field=models.ForeignKey(default='BSIT', on_delete=django.db.models.deletion.CASCADE, to='AlumniManagement.course'),
        ),
        migrations.AddField(
            model_name='alumni_demographic_profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
    ]
