# Generated by Django 4.2.1 on 2023-05-31 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlumniManagement', '0003_current_job_barangay_current_job_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='previous_job',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AlumniManagement.country'),
        ),
    ]
