# Generated by Django 4.2.1 on 2023-05-31 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlumniManagement', '0004_previous_job_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='previous_job',
            name='barangay',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='AlumniManagement.barangay'),
        ),
        migrations.AddField(
            model_name='previous_job',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AlumniManagement.city'),
        ),
        migrations.AddField(
            model_name='previous_job',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AlumniManagement.province'),
        ),
    ]
