# Generated by Django 4.2.1 on 2023-06-07 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlumniManagement', '0005_previous_job_barangay_previous_job_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current_job',
            name='company_address',
        ),
    ]
