# Generated by Django 4.2.1 on 2023-05-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlumniManagement', '0005_course_field_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educational_attainment',
            name='id',
        ),
        migrations.AddField(
            model_name='educational_attainment',
            name='graduation_date',
            field=models.DateField(default='2021-02-05'),
        ),
        migrations.AddField(
            model_name='educational_attainment',
            name='honor',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='educational_attainment',
            name='graduate_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Graduate',
        ),
    ]
