# Generated by Django 4.2.1 on 2023-05-22 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlumniManagement', '0006_remove_educational_attainment_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Educational_Attainment',
            new_name='Graduate',
        ),
    ]
