# Generated by Django 4.2.1 on 2023-06-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlumniManagement', '0006_remove_current_job_company_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduate',
            name='graduation_date',
            field=models.DateField(),
        ),
    ]
