# Generated by Django 4.2.1 on 2023-05-23 02:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlumniManagement', '0007_rename_educational_attainment_graduate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni_demographic_profile',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2001, 5, 5)),
        ),
    ]
