# Generated by Django 4.2.1 on 2023-06-11 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlumniManagement', '0007_alter_graduate_graduation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graduate',
            old_name='alumni_id',
            new_name='alumni',
        ),
        migrations.RemoveField(
            model_name='previous_job',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='current_job',
        ),
        migrations.AddField(
            model_name='segment',
            name='graduate',
            field=models.ForeignKey(default='G10000', on_delete=django.db.models.deletion.CASCADE, to='AlumniManagement.graduate'),
        ),
    ]
