# Generated by Django 4.2.1 on 2023-06-12 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlumniManagement', '0008_rename_alumni_id_graduate_alumni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='previous_job',
            name='current_job',
            field=models.ForeignKey(default='JOB103', on_delete=django.db.models.deletion.CASCADE, to='AlumniManagement.current_job'),
        ),
    ]
