# Generated by Django 4.2.1 on 2023-05-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlumniManagement', '0008_alter_alumni_demographic_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni_demographic_profile',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
