# Generated by Django 4.2.1 on 2023-06-12 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlumniManagement', '0009_previous_job_current_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previous_job',
            name='current_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlumniManagement.current_job'),
        ),
    ]
