# Generated by Django 4.2.1 on 2023-05-24 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AlumniManagement', '0009_alter_alumni_demographic_profile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni_demographic_profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
