# Generated by Django 4.2.1 on 2023-05-30 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlumniManagement', '0010_alumni_demographic_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni_demographic_profile',
            old_name='gender',
            new_name='sex',
        ),
    ]
