# Generated by Django 4.2.1 on 2023-06-12 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlumniManagement', '0010_alter_previous_job_current_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previous_job',
            name='current_job',
        ),
    ]
