# Generated by Django 4.2.1 on 2023-05-30 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlumniManagement', '0011_rename_gender_alumni_demographic_profile_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni_demographic_profile',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlumniManagement.course'),
        ),
        migrations.AlterField(
            model_name='alumni_demographic_profile',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
    ]
