# Generated by Django 4.2.1 on 2023-05-30 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlumniManagement', '0011_country_province_city_barangay'),
        ('AlumniManagement', '0012_alter_alumni_demographic_profile_course_id_and_more'),
    ]

    operations = [
    ]
